/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.receptionist;

import business.enterprise.Enterprise;
import business.network.Network;
import business.person.PersonDirectory;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userInterface.supervisior.ShowInQueueJPanel;

/**
 *
 * @author ajinkya
 */
public class ReceptionistWorkAeraJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    private UserAccount user;
    private Enterprise enterprise;
    private Network network;
    /**
     * Creates new form ReceptionistWorkAeraJPanel
     */
    public ReceptionistWorkAeraJPanel() {
        initComponents();
        jScrollPane1.setVisible(Boolean.FALSE);
        jScrollPane1.setEnabled(false);
        outQueueJTable.setVisible(false);
    }

    public ReceptionistWorkAeraJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network) {
        this();
        this.userProcessContainer = userProcessContainer;
        this.user = account;
        this.personDirectory = network.getPersonDirectory();
        this.enterprise = enterprise;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getAppointmentJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outQueueJTable = new javax.swing.JTable();
        salartManagementJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 254, 242));

        getAppointmentJButton.setBackground(new java.awt.Color(237, 238, 225));
        getAppointmentJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        getAppointmentJButton.setText("Get Appointment");
        getAppointmentJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAppointmentJButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(237, 238, 225));
        jButton1.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jButton1.setText("Show Out Queue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        outQueueJTable.setBackground(new java.awt.Color(237, 238, 225));
        outQueueJTable.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        outQueueJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(outQueueJTable);

        salartManagementJButton.setBackground(new java.awt.Color(237, 238, 225));
        salartManagementJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        salartManagementJButton.setText("Salary Manageent");
        salartManagementJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salartManagementJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(getAppointmentJButton)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(salartManagementJButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getAppointmentJButton)
                    .addComponent(jButton1)
                    .addComponent(salartManagementJButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void getAppointmentJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAppointmentJButtonActionPerformed
        GetAppointmentJPanel viewCrime = new GetAppointmentJPanel(userProcessContainer, personDirectory, user,enterprise);
        userProcessContainer.add(viewCrime) ;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_getAppointmentJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jScrollPane1.setVisible(true);
        jScrollPane1.setEnabled(true);
        outQueueJTable.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salartManagementJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salartManagementJButtonActionPerformed
        ManageSalaryJPanel viewCrime = new ManageSalaryJPanel(userProcessContainer, personDirectory, enterprise,user,network);
        userProcessContainer.add(viewCrime) ;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_salartManagementJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton getAppointmentJButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable outQueueJTable;
    private javax.swing.JButton salartManagementJButton;
    // End of variables declaration//GEN-END:variables
}
