/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.AuthorityOfficer;

import business.person.Person;
import business.workQueue.LicenseWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ajinkya
 */
public class ViewWorkRequestJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private LicenseWorkRequest request;
    private Person holder;
    
    /**
     * Creates new form ViewWorkRequestJPanel
     */
    public ViewWorkRequestJPanel(JPanel userProcessContainer, LicenseWorkRequest request) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.holder = request.getHolder();
        displayFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reasonTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        licenseJTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        senderNameJTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        personNameJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 254, 242));

        messageJTextField.setBackground(new java.awt.Color(237, 238, 225));
        messageJTextField.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        messageJTextField.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel3.setText("Message");

        jLabel4.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel4.setText("Violations(if any)");

        reasonTextArea.setBackground(new java.awt.Color(237, 238, 225));
        reasonTextArea.setColumns(20);
        reasonTextArea.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        reasonTextArea.setRows(5);
        reasonTextArea.setEnabled(false);
        jScrollPane1.setViewportView(reasonTextArea);

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel5.setText("Suggest License Period (Months)");

        licenseJTextField.setBackground(new java.awt.Color(237, 238, 225));
        licenseJTextField.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        licenseJTextField.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel1.setText("Sender Name");

        senderNameJTextField.setBackground(new java.awt.Color(237, 238, 225));
        senderNameJTextField.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        senderNameJTextField.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel2.setText("Requested Person Name");

        personNameJTextField.setBackground(new java.awt.Color(237, 238, 225));
        personNameJTextField.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        personNameJTextField.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel6.setText("Details of Incoming Request");

        jButton1.setBackground(new java.awt.Color(237, 238, 225));
        jButton1.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jButton1.setText("< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personNameJTextField)
                    .addComponent(senderNameJTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(licenseJTextField)
                        .addGap(130, 130, 130))
                    .addComponent(jScrollPane1)
                    .addComponent(messageJTextField))
                .addGap(207, 207, 207))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(personNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(senderNameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(messageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(licenseJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(9, 9, 9))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField licenseJTextField;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JTextField personNameJTextField;
    private javax.swing.JTextArea reasonTextArea;
    private javax.swing.JTextField senderNameJTextField;
    // End of variables declaration//GEN-END:variables

    private void displayFields() {
        licenseJTextField.setText(Integer.toString(request.getLicensePeriod()));
        reasonTextArea.setText(request.getReason());
        messageJTextField.setText(request.getMessage());
        personNameJTextField.setText(holder.getFirstName()+" "+holder.getLastName());
        senderNameJTextField.setText(request.getSender().toString());
    }
}
