/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.patrollingOfficer;

import business.crime.CrimeIncident;
import business.person.Person;
import business.person.PersonDirectory;
import business.workQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ajinkya
 */
public class InvestigationJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private CrimeIncident crime;
    private PersonDirectory personDirectory;
    private DefaultListModel mainListModel;
    private DefaultListModel prevListModel;
    private WorkRequest request;
    /**
     * Creates new form InvestigationJPanel
     * @param userProcessContainer
     * @param crime
     * @param personDirectory
     */
    public InvestigationJPanel(JPanel userProcessContainer, CrimeIncident crime, PersonDirectory personDirectory, WorkRequest work) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.crime = crime;
        this.personDirectory = personDirectory;
        mainListModel = new DefaultListModel();
        prevListModel = new DefaultListModel();
        personJList.setModel(prevListModel);
        personMainJList.setModel(mainListModel);
        request = work;
        populateList();
        DateFormat df = new SimpleDateFormat("MM/DD/YYYY");
        
        try{
            crimeIDTextField.setText(crime.toString());
            crimeDateTextField.setText(df.format(crime.getCrimeHappenedOn()));
            descrptionJTextArea.setText(crime.getDescription());
            addedByJTextField.setText(crime.getAddedBy().toString());
        }
        catch(Exception e){
            
        }
    }
    
    public void populateList(){
        
        int count =0;
        for(String personKeys : personDirectory.getPersonList().keySet()){
            Person newPerson = personDirectory.getPersonList().get(personKeys);
            prevListModel.addElement(newPerson);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        crimeIDTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addedByJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        crimeDateTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descrptionJTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        personJList = new javax.swing.JList();
        deleteButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        completeJButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        personMainJList = new javax.swing.JList();

        setBackground(new java.awt.Color(255, 254, 242));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Investigation Report");

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel2.setText("Crime ID");

        crimeIDTextField.setBackground(new java.awt.Color(237, 238, 225));
        crimeIDTextField.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        crimeIDTextField.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel4.setText("Crime Added By ");

        addedByJTextField.setBackground(new java.awt.Color(237, 238, 225));
        addedByJTextField.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        addedByJTextField.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel3.setText("Date");

        crimeDateTextField.setBackground(new java.awt.Color(237, 238, 225));
        crimeDateTextField.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        crimeDateTextField.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel7.setText("Description");

        descrptionJTextArea.setBackground(new java.awt.Color(237, 238, 225));
        descrptionJTextArea.setColumns(20);
        descrptionJTextArea.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        descrptionJTextArea.setRows(5);
        descrptionJTextArea.setEnabled(false);
        jScrollPane1.setViewportView(descrptionJTextArea);

        jLabel5.setFont(new java.awt.Font("Helvetica", 1, 16)); // NOI18N
        jLabel5.setText("Crime Details");

        jLabel6.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel6.setText("Add Involved People");

        jLabel8.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel9.setText("Select from List");

        personJList.setBackground(new java.awt.Color(237, 238, 225));
        personJList.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        personJList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(personJList);

        deleteButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        deleteButton.setText("<");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        backJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        completeJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        completeJButton.setText("Complete Investigation");
        completeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeJButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        addButton.setText(">");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        personMainJList.setBackground(new java.awt.Color(237, 238, 225));
        personMainJList.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        personMainJList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(personMainJList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backJButton)
                                .addGap(134, 134, 134)
                                .addComponent(completeJButton)))
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(crimeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(crimeDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(24, 24, 24)
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(addedByJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(crimeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addedByJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(crimeDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(completeJButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        DefaultListModel perviousModel =  (DefaultListModel) personJList.getModel();
        Person selectedPerson = (Person) personJList.getSelectedValue();
        perviousModel.removeElement(selectedPerson);
        
        mainListModel.addElement(selectedPerson);
        personMainJList.setModel(mainListModel);
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        Person selectedPerson = (Person) personMainJList.getSelectedValue();
        mainListModel.removeElement(selectedPerson);
        prevListModel.addElement(selectedPerson);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void completeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeJButtonActionPerformed
        
        int listItems = mainListModel.getSize(); //Accessing Models to count numbers of elements.
        for(int i=0;i<listItems;i++){
            Person selectedPerson = (Person) mainListModel.getElementAt(i);
            crime.getInvolvedpeople().addPerson(selectedPerson);
        }
        JOptionPane.showMessageDialog(personJList, "Selected People are Added to the list");
        crime.setStatus("Investigation Done");
        request.setStatus("Investigation Done");
        request.setMessage("People are set for trials. Please proceed with next step.");
        request.setResolveDate(new Date());
        mainListModel.removeAllElements();
    }//GEN-LAST:event_completeJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField addedByJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton completeJButton;
    private javax.swing.JTextField crimeDateTextField;
    private javax.swing.JTextField crimeIDTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextArea descrptionJTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList personJList;
    private javax.swing.JList personMainJList;
    // End of variables declaration//GEN-END:variables
}
