/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.patrollingOfficer;

import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.PatrollingOrganization;
import business.person.PersonDirectory;
import business.schedule.Schedule;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userInterface.supervisior.PatrollingScheduleJPanel;
import userInterface.supervisior.ShowInQueueJPanel;
/**
 *
 * @author ajinkya
 */
public class PatrollingOfficerWorkArea extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount user;
    private PersonDirectory personDirectory;
    private Schedule schedule;
    private PatrollingOrganization organization;
    /**
     * Creates new form PatrollingOfficerWorkArea
     */
    public PatrollingOfficerWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise,Network network) {
        initComponents();
        officerNameJLabel.setText("Welcome "+ account.getEmployee().toString());
        this.userProcessContainer = userProcessContainer;
        this.user = account;
        this.personDirectory = network.getPersonDirectory();
        this.organization = (PatrollingOrganization) organization;
        this.schedule = this.organization.getSchedule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        officerNameJLabel = new javax.swing.JLabel();
        showInQueueJButton = new javax.swing.JButton();
        viewScheduleJButton = new javax.swing.JButton();
        completeJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 254, 242));

        officerNameJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        officerNameJLabel.setText("Welcome Name");

        showInQueueJButton.setBackground(new java.awt.Color(237, 238, 225));
        showInQueueJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        showInQueueJButton.setText("Incoming Requests");
        showInQueueJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInQueueJButtonActionPerformed(evt);
            }
        });

        viewScheduleJButton.setBackground(new java.awt.Color(237, 238, 225));
        viewScheduleJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        viewScheduleJButton.setText("View Schedule");
        viewScheduleJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewScheduleJButtonActionPerformed(evt);
            }
        });

        completeJButton.setBackground(new java.awt.Color(237, 238, 225));
        completeJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        completeJButton.setText("Complete Schedule");
        completeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(officerNameJLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showInQueueJButton)
                        .addGap(18, 18, 18)
                        .addComponent(viewScheduleJButton)
                        .addGap(18, 18, 18)
                        .addComponent(completeJButton)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(officerNameJLabel)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showInQueueJButton)
                    .addComponent(viewScheduleJButton)
                    .addComponent(completeJButton))
                .addContainerGap(200, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showInQueueJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInQueueJButtonActionPerformed
        ShowInQueueJPanel viewCrime = new ShowInQueueJPanel(userProcessContainer,user.getInQueue(), personDirectory);
        userProcessContainer.add(viewCrime) ;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_showInQueueJButtonActionPerformed

    private void viewScheduleJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewScheduleJButtonActionPerformed
        PatrollingScheduleJPanel viewSchedule = new PatrollingScheduleJPanel(userProcessContainer,schedule, organization,user);
        userProcessContainer.add(viewSchedule);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewScheduleJButtonActionPerformed

    private void completeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeJButtonActionPerformed
        CompleteScheduleJPanel viewSchedule = new CompleteScheduleJPanel(userProcessContainer, user, schedule);
        userProcessContainer.add(viewSchedule);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_completeJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton completeJButton;
    private javax.swing.JLabel officerNameJLabel;
    private javax.swing.JButton showInQueueJButton;
    private javax.swing.JButton viewScheduleJButton;
    // End of variables declaration//GEN-END:variables
}
