/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.investigator;

import business.crime.CrimeIncident;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import business.person.PersonDirectory;
import business.userAccount.UserAccount;
import business.workQueue.InvestigationWorkRequest;
import business.workQueue.WorkQueue;
import business.workQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.patrollingOfficer.InvestigationJPanel;

/**
 *
 * @author ajinkya
 */
public class InvestigatorWorkArea extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private WorkQueue currentQueue;
    private PersonDirectory personDirectory;
    /**
     * Creates new form InvestigatorWorkArea
     */
    public InvestigatorWorkArea() {
        initComponents();
    }

    public InvestigatorWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network) {
        this();
        this.userProcessContainer = userProcessContainer;
        welcomeJLabel.setText("Welcome "+account.getEmployee().getPerson());
        currentQueue = account.getInQueue();
        this.personDirectory = network.getPersonDirectory();
        populateTable();
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) inQueueJTable.getModel();
        model.setRowCount(0);
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        
        for(Integer queueKeys : currentQueue.getWorkRequstList().keySet()){
            InvestigationWorkRequest request = (InvestigationWorkRequest) currentQueue.getWorkRequstList().get(queueKeys);
            Object row[] = new Object[5];
            row[0] = request.getRequestDate();
            row[1] = request.getSender().getEmployee();
            row[2] = request.getMessage();
            row[3] = request;
            row[4] = request.getIncident();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeJLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        inQueueJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        investigateCrimeJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 254, 242));

        welcomeJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        welcomeJLabel.setText("Welcome");

        inQueueJTable.setBackground(new java.awt.Color(237, 238, 225));
        inQueueJTable.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        inQueueJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Date", "Sender", "Message", "Status", "CrimeID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(inQueueJTable);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setText("Your Incoming Queue");

        investigateCrimeJButton.setBackground(new java.awt.Color(237, 238, 225));
        investigateCrimeJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        investigateCrimeJButton.setText("Investigate Crime");
        investigateCrimeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investigateCrimeJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeJLabel)
                            .addComponent(jLabel1)
                            .addComponent(investigateCrimeJButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeJLabel)
                .addGap(31, 31, 31)
                .addComponent(investigateCrimeJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void investigateCrimeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investigateCrimeJButtonActionPerformed
       int i = inQueueJTable.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(null, "Please Select Any Crime Event");
        }
        else{
            CrimeIncident crime = (CrimeIncident) inQueueJTable.getValueAt(i, 4);
            WorkRequest workRequest = (WorkRequest) inQueueJTable.getValueAt(i, 3);
            InvestigationJPanel  investCrime = new InvestigationJPanel(userProcessContainer,crime, personDirectory, workRequest);
            userProcessContainer.add(investCrime);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_investigateCrimeJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable inQueueJTable;
    private javax.swing.JButton investigateCrimeJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel welcomeJLabel;
    // End of variables declaration//GEN-END:variables
}
