/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.supervisior;

import business.crime.CrimeIncident;
import business.person.PersonDirectory;
import business.workQueue.InvestigationWorkRequest;
import business.workQueue.WorkQueue;
import business.workQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.patrollingOfficer.InvestigationJPanel;

/**
 *
 * @author ajinkya
 */
public class ShowInQueueJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private WorkQueue currentQueue;
    private PersonDirectory personDirectory;
    /**
     * Creates new form ShowInQueueJPanel
     * @param userProcessContainer
     * @param outQueue
     */
    public ShowInQueueJPanel(JPanel userProcessContainer, WorkQueue outQueue) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.currentQueue = outQueue;
    }
    
    //This constuctor will be used by Patrolling Officers or Detectives
    public ShowInQueueJPanel(JPanel userProcessContainer, WorkQueue outQueue, PersonDirectory personDirectory) {
        this(userProcessContainer, outQueue);
        this.personDirectory = personDirectory;
        populateTable();
        int i=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inQueueJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 254, 242));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Incoming Requests");

        inQueueJTable.setBackground(new java.awt.Color(237, 238, 225));
        inQueueJTable.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        inQueueJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Date", "Sender", "Message", "Status", "CrimeID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(inQueueJTable);

        backJButton.setBackground(new java.awt.Color(237, 238, 225));
        backJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(237, 238, 225));
        jButton1.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jButton1.setText("Enter Investigation Results");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(jButton1))
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = inQueueJTable.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(null, "Please Select Any Crime Event");
        }
        else{
            CrimeIncident crime = (CrimeIncident) inQueueJTable.getValueAt(i, 4);
            WorkRequest workRequest = (WorkRequest) inQueueJTable.getValueAt(i, 3);
            InvestigationJPanel  investCrime = new InvestigationJPanel(userProcessContainer,crime, personDirectory, workRequest);
            userProcessContainer.add(investCrime);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) inQueueJTable.getModel();
        model.setRowCount(0);
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        
        for(Integer queueKeys : currentQueue.getWorkRequstList().keySet()){
            InvestigationWorkRequest request = (InvestigationWorkRequest) currentQueue.getWorkRequstList().get(queueKeys);
            Object row[] = new Object[5];
            row[0] = request.getRequestDate();
            row[1] = request.getSender().getEmployee();
            row[2] = request.getMessage();
            row[3] = request;
            row[4] = request.getIncident();
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JTable inQueueJTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
