/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.supervisior;

import business.crime.CrimeIncident;
import business.crime.CrimeRecord;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import business.organization.PatrollingOrganization;
import business.person.PersonDirectory;
import business.schedule.Schedule;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.receptionist.ManageSalaryJPanel;

/**
 *
 * @author ajinkya
 */
public class SupervisiorWorkArea extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private CrimeRecord crimeRecords;
    private UserAccount user;
    private Enterprise enterprise;
    private Schedule schedule;
    private Organization organization;
    private PersonDirectory personDirectory;
    private Network network;
    /**
     * Creates new form SupervisiorWorkArea
     */
    public SupervisiorWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization, Network network, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.crimeRecords = network.getCrimeRecords();
        
        this.user = account;
        this.enterprise = enterprise;
        this.organization = organization;
        this.network = network;
        this.personDirectory = this.network.getPersonDirectory();
        populateTable();
        
        for(Integer organizationKeys : enterprise.getOrganizationDirectory().getOrganizationDirectory().keySet()){
            Organization currentOrganization = enterprise.getOrganizationDirectory().getOrganizationDirectory().get(organizationKeys);
            if(currentOrganization instanceof PatrollingOrganization){
                PatrollingOrganization newOrg = (PatrollingOrganization) currentOrganization;
                this.schedule = newOrg.getSchedule();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        crimeReportJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        showInQueueButton = new javax.swing.JButton();
        showOutQueueJButton = new javax.swing.JButton();
        investigateJButton = new javax.swing.JButton();
        viewCrimeJButton = new javax.swing.JButton();
        patrollingScheduleJButton = new javax.swing.JButton();
        manageSalaryJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 254, 242));

        crimeReportJTable.setBackground(new java.awt.Color(237, 238, 225));
        crimeReportJTable.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        crimeReportJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Reported By", "Status", "Description", "Crime ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(crimeReportJTable);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setText("Crime Records in Our Network");

        showInQueueButton.setBackground(new java.awt.Color(237, 238, 225));
        showInQueueButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        showInQueueButton.setText("Show Inbox");
        showInQueueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInQueueButtonActionPerformed(evt);
            }
        });

        showOutQueueJButton.setBackground(new java.awt.Color(237, 238, 225));
        showOutQueueJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        showOutQueueJButton.setText("Show Out Queue");
        showOutQueueJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showOutQueueJButtonActionPerformed(evt);
            }
        });

        investigateJButton.setBackground(new java.awt.Color(237, 238, 225));
        investigateJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        investigateJButton.setText("Investigate Crime");
        investigateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                investigateJButtonActionPerformed(evt);
            }
        });

        viewCrimeJButton.setBackground(new java.awt.Color(237, 238, 225));
        viewCrimeJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        viewCrimeJButton.setText("View Crime Details");
        viewCrimeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCrimeJButtonActionPerformed(evt);
            }
        });

        patrollingScheduleJButton.setBackground(new java.awt.Color(237, 238, 225));
        patrollingScheduleJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        patrollingScheduleJButton.setText("Patrolling Schedule");
        patrollingScheduleJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patrollingScheduleJButtonActionPerformed(evt);
            }
        });

        manageSalaryJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        manageSalaryJButton.setText("Salary Management");
        manageSalaryJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSalaryJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(viewCrimeJButton)
                                .addGap(18, 18, 18)
                                .addComponent(investigateJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(showOutQueueJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(showInQueueButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageSalaryJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(patrollingScheduleJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(investigateJButton)
                    .addComponent(viewCrimeJButton)
                    .addComponent(patrollingScheduleJButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showOutQueueJButton)
                    .addComponent(showInQueueButton)
                    .addComponent(manageSalaryJButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewCrimeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCrimeJButtonActionPerformed
        
        int i = crimeReportJTable.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(null, "Please Select Any Crime Event");
        }
        else{
            CrimeIncident crime = (CrimeIncident) crimeReportJTable.getValueAt(i, 4);
            
            ViewCrimeDetailsJPanel viewCrime = new ViewCrimeDetailsJPanel(userProcessContainer,crime,enterprise,personDirectory,user,network);
            userProcessContainer.add(viewCrime);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_viewCrimeJButtonActionPerformed

    private void investigateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_investigateJButtonActionPerformed
        int i = crimeReportJTable.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(null, "Please Select Any Crime Event");
        }
        else{
            CrimeIncident crime = (CrimeIncident) crimeReportJTable.getValueAt(i, 4);
            SendInvestigatorJPanel viewCrime = new SendInvestigatorJPanel(userProcessContainer,crime,user,enterprise,crimeRecords);
            userProcessContainer.add(viewCrime);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_investigateJButtonActionPerformed

    private void showOutQueueJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showOutQueueJButtonActionPerformed
        ShowOutQueueJPanel viewCrime = new ShowOutQueueJPanel(userProcessContainer,user.getOutQueue());
        userProcessContainer.add(viewCrime);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_showOutQueueJButtonActionPerformed

    private void showInQueueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInQueueButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showInQueueButtonActionPerformed

    private void patrollingScheduleJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patrollingScheduleJButtonActionPerformed
        PatrollingScheduleJPanel viewCrime = new PatrollingScheduleJPanel(userProcessContainer,schedule, organization,user);
        userProcessContainer.add(viewCrime);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_patrollingScheduleJButtonActionPerformed

    private void manageSalaryJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSalaryJButtonActionPerformed
        ManageSalaryJPanel viewCrime = new ManageSalaryJPanel(userProcessContainer, personDirectory, enterprise,user,network);
        userProcessContainer.add(viewCrime) ;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageSalaryJButtonActionPerformed
    
    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) crimeReportJTable.getModel();
        model.setRowCount(0);
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        for(Integer crimeKeys : crimeRecords.getCrimeRecord().keySet()){
            CrimeIncident incident = crimeRecords.getCrimeRecord().get(crimeKeys);
            
            Object row[] = new Object[5];
            row[0] = df.format(incident.getCrimeHappenedOn());
            row[1] = incident.getAddedBy();
            row[2] = incident.getStatus();
            row[3] = incident.getDescription();
            row[4] = incident;
            model.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable crimeReportJTable;
    private javax.swing.JButton investigateJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageSalaryJButton;
    private javax.swing.JButton patrollingScheduleJButton;
    private javax.swing.JButton showInQueueButton;
    private javax.swing.JButton showOutQueueJButton;
    private javax.swing.JButton viewCrimeJButton;
    // End of variables declaration//GEN-END:variables
}
