/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.supervisior;

import business.crime.CrimeIncident;
import business.enterprise.Enterprise;
import business.network.Network;
import business.person.Person;
import business.person.PersonDirectory;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userInterface.investigator.RevokeLicenseRequestJPanel;

/**
 *
 * @author ajinkya
 */
public class ViewCrimeDetailsJPanel extends javax.swing.JPanel {
    private CrimeIncident incident;
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    private Enterprise enterprise;
    private UserAccount user; 
    private Network network;
    /**
     * Creates new form ViewCrimeDetailsJPanel
     * @param userProcessContainer
     * @param incident
     */
    public ViewCrimeDetailsJPanel(JPanel userProcessContainer, CrimeIncident incident, Enterprise enterprise, PersonDirectory personDirectory,UserAccount user, Network network) {
        initComponents();
        this.incident = incident;
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        this.enterprise = enterprise;
        crimeIDTextField.setText(incident.toString());
        this.user = user;
        this.network = network;
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
        try{
            
            officerTextField.setText(incident.getAssignedTo().getFirstName());
            populateTable();
        }
        catch(Exception e){
            
        }
        finally{
            crimeDateTextField.setText(df.format(incident.getCrimeHappenedOn()));
            descrptionJTextArea.setText(incident.getDescription());
            statusTextField.setText(incident.getStatus());
            addedByJTextField.setText(incident.getAddedBy().toString());
        }
    }

    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) personReportJTable.getModel();
        model.setRowCount(0);
        
        for(String personKeys : incident.getInvolvedpeople().getPersonList().keySet()){
            Person person = incident.getInvolvedpeople().getPersonList().get(personKeys);
            Object row[] = new Object[3];
            row[0] = person;
            
            row[1] = person.getAddress();
            row[2] = person.getDoesHaveLicense();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        crimeIDTextField = new javax.swing.JTextField();
        crimeDateTextField = new javax.swing.JTextField();
        statusTextField = new javax.swing.JTextField();
        addedByJTextField = new javax.swing.JTextField();
        officerTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descrptionJTextArea = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        personReportJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        sendRequstJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 254, 242));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Crime Incident Details");

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel2.setText("Crime ID");

        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel3.setText("Date");

        jLabel4.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel4.setText("Crime Added By ");

        jLabel5.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel5.setText("Investigating Officer");

        jLabel6.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel6.setText("Status");

        jLabel7.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel7.setText("Description");

        crimeIDTextField.setBackground(new java.awt.Color(237, 238, 225));
        crimeIDTextField.setEnabled(false);

        crimeDateTextField.setBackground(new java.awt.Color(237, 238, 225));
        crimeDateTextField.setEnabled(false);

        statusTextField.setBackground(new java.awt.Color(237, 238, 225));
        statusTextField.setEnabled(false);

        addedByJTextField.setBackground(new java.awt.Color(237, 238, 225));
        addedByJTextField.setEnabled(false);

        officerTextField.setBackground(new java.awt.Color(237, 238, 225));
        officerTextField.setEnabled(false);

        descrptionJTextArea.setBackground(new java.awt.Color(237, 238, 225));
        descrptionJTextArea.setColumns(20);
        descrptionJTextArea.setRows(5);
        descrptionJTextArea.setEnabled(false);
        jScrollPane1.setViewportView(descrptionJTextArea);

        jLabel8.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel8.setText("Involved People");

        personReportJTable.setBackground(new java.awt.Color(237, 238, 225));
        personReportJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Address", "Does have License"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(personReportJTable);

        backJButton.setBackground(new java.awt.Color(237, 238, 225));
        backJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        backJButton.setText("< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        sendRequstJButton.setText("Send Lincese Revocation Request");
        sendRequstJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRequstJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(34, 34, 34)
                                        .addComponent(crimeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel4)
                                        .addGap(28, 28, 28)
                                        .addComponent(addedByJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(62, 62, 62)
                                        .addComponent(crimeDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(officerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(50, 50, 50)
                                        .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(47, 47, 47)
                                .addComponent(jScrollPane1)))
                        .addContainerGap())
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backJButton)
                            .addGap(264, 264, 264)
                            .addComponent(sendRequstJButton)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jScrollPane2)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(crimeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addedByJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(crimeDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(officerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(sendRequstJButton))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void sendRequstJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRequstJButtonActionPerformed
        int i = personReportJTable.getSelectedRow();
        if(i<0){
            JOptionPane.showMessageDialog(null, "Please Select Any Person");
        }
        else{
            Person selectedPerson = (Person) personReportJTable.getValueAt(i, 0);
            if(selectedPerson.getDoesHaveLicense()==1){
                //CrimeIncident crime = (CrimeIncident) personReportJTable.getValueAt(i, 4);
            
                RevokeLicenseRequestJPanel revoke = new RevokeLicenseRequestJPanel(userProcessContainer, personDirectory, selectedPerson, user, enterprise,network);
                userProcessContainer.add(revoke);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            else{
                JOptionPane.showMessageDialog(backJButton, "Selected Person Doesn't Have Any License");
            }
            
        }
    }//GEN-LAST:event_sendRequstJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addedByJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField crimeDateTextField;
    private javax.swing.JTextField crimeIDTextField;
    private javax.swing.JTextArea descrptionJTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField officerTextField;
    private javax.swing.JTable personReportJTable;
    private javax.swing.JButton sendRequstJButton;
    private javax.swing.JTextField statusTextField;
    // End of variables declaration//GEN-END:variables
}
