/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.person;

import business.crime.CrimeRecord;
import business.network.Network;
import business.person.Person;
import business.person.PersonDirectory;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.clerkInterface.CrimeAddPanel;


/**
 *
 * @author ajinkya
 */
public class PersonWorkArea extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount user;
    private Network network;
    private PersonDirectory personDirectory;
    private Person person;
    private CrimeRecord crimeRecords;
    
    /**
     * Creates new form PersonWorkArea
     */
    public PersonWorkArea(JPanel userProcessContianer, UserAccount user, Network network) {
        initComponents();
        this.userProcessContainer = userProcessContianer;
        this.user = user;
        this.network = network;
        //JOptionPane.showMessageDialog(WelcomeJLabel, network);
        this.personDirectory = network.getPersonDirectory();
        this.crimeRecords = this.network.getCrimeRecords();
        this.person = personDirectory.searchPerson(user.getUsername());
        WelcomeJLabel.setText("Welcome "+ personDirectory.getPersonList().get(user.getUsername()).toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeJLabel = new javax.swing.JLabel();
        addCrimeButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 254, 242));

        WelcomeJLabel.setText("jLabel1");

        addCrimeButton.setBackground(new java.awt.Color(237, 238, 225));
        addCrimeButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        addCrimeButton.setText("Add a Crime");
        addCrimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCrimeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(addCrimeButton)
                .addGap(0, 505, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WelcomeJLabel)
                .addGap(60, 60, 60)
                .addComponent(addCrimeButton)
                .addContainerGap(264, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addCrimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCrimeButtonActionPerformed
        // TODO add your handling code here:
        CrimeAddPanel addCrime = new CrimeAddPanel(userProcessContainer, crimeRecords, user, person);
        userProcessContainer.add(addCrime);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addCrimeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WelcomeJLabel;
    private javax.swing.JButton addCrimeButton;
    // End of variables declaration//GEN-END:variables
}
