/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.federalOfficer;

import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import business.person.PersonDirectory;
import business.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userInterface.adminRole.ManageOrganizationJPanel;

/**
 *
 * @author ajinkya
 */
public class FederalOfficerWorkArea extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Network network;
    private PersonDirectory personDirectory;
    /**
     * Creates new form FederalOfficerWorkArea
     */
    public FederalOfficerWorkArea() {
        initComponents();
    }

    public FederalOfficerWorkArea(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network) {
        this();
        welcomeJLabel.setText("Wecome "+ account.getEmployee().toString() );
        this.userProcessContainer = userProcessContainer;
        this.network = network;
        this.personDirectory = this.network.getPersonDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeJLabel = new javax.swing.JLabel();
        addPersonRecordJButton = new javax.swing.JButton();
        manageUserAccountJButton = new javax.swing.JButton();
        viewRecordsJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 254, 242));

        welcomeJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        welcomeJLabel.setText("Welcome");

        addPersonRecordJButton.setBackground(new java.awt.Color(237, 238, 225));
        addPersonRecordJButton.setText("Add Person Records");
        addPersonRecordJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonRecordJButtonActionPerformed(evt);
            }
        });

        manageUserAccountJButton.setBackground(new java.awt.Color(237, 238, 225));
        manageUserAccountJButton.setText("Manage User Accounts");
        manageUserAccountJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserAccountJButtonActionPerformed(evt);
            }
        });

        viewRecordsJButton.setBackground(new java.awt.Color(237, 238, 225));
        viewRecordsJButton.setText("View Records");
        viewRecordsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRecordsJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeJLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addPersonRecordJButton)
                        .addGap(18, 18, 18)
                        .addComponent(manageUserAccountJButton)
                        .addGap(18, 18, 18)
                        .addComponent(viewRecordsJButton)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeJLabel)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPersonRecordJButton)
                    .addComponent(manageUserAccountJButton)
                    .addComponent(viewRecordsJButton))
                .addContainerGap(229, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addPersonRecordJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonRecordJButtonActionPerformed
        ManagePersonJPanel managePersonJPanel = new ManagePersonJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("managePersonJPanel", managePersonJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addPersonRecordJButtonActionPerformed

    private void viewRecordsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRecordsJButtonActionPerformed
        ViewPersonRecordJPanel managePersonJPanel = new ViewPersonRecordJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("managePersonJPanel", managePersonJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewRecordsJButtonActionPerformed

    private void manageUserAccountJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserAccountJButtonActionPerformed
        ManagePersonUserAccountJPanel managePersonJPanel = new ManagePersonUserAccountJPanel(userProcessContainer, personDirectory);
        userProcessContainer.add("managePersonJPanel", managePersonJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageUserAccountJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPersonRecordJButton;
    private javax.swing.JButton manageUserAccountJButton;
    private javax.swing.JButton viewRecordsJButton;
    private javax.swing.JLabel welcomeJLabel;
    // End of variables declaration//GEN-END:variables
}
