/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.federalOfficer;

import business.network.Network;
import business.person.Person;
import business.person.PersonDirectory;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static userInterface.receptionist.GetAppointmentJPanel.validateEmail;
import static userInterface.receptionist.GetAppointmentJPanel.validateName;
import static userInterface.receptionist.GetAppointmentJPanel.validatePhone;
import static userInterface.receptionist.GetAppointmentJPanel.validateSSN;

/**
 *
 * @author ajinkya
 */
public class ManagePersonJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private PersonDirectory personDirectory;
    /**
     * Creates new form ManagePersonJPanel
     */
    public ManagePersonJPanel() {
        initComponents();
    }

    ManagePersonJPanel(JPanel userProcessContainer, PersonDirectory personDirectory) {
        this();
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        fnameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lnameJTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ssnJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailJTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        wPhoneJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        birthdateTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        addJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 254, 242));

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel2.setText("First Name");

        fnameJTextField.setBackground(new java.awt.Color(237, 238, 225));
        fnameJTextField.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel3.setText("Last Name");

        lnameJTextField.setBackground(new java.awt.Color(237, 238, 225));
        lnameJTextField.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel6.setText("SSN");

        ssnJTextField.setBackground(new java.awt.Color(237, 238, 225));
        ssnJTextField.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel7.setText("Email");

        emailJTextField.setBackground(new java.awt.Color(237, 238, 225));
        emailJTextField.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel8.setText("Home Phone");

        wPhoneJTextField.setBackground(new java.awt.Color(237, 238, 225));
        wPhoneJTextField.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        wPhoneJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wPhoneJTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel9.setText("BirthDate");

        birthdateTextField.setBackground(new java.awt.Color(237, 238, 225));
        birthdateTextField.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel10.setText("Address");

        addressTextArea.setBackground(new java.awt.Color(237, 238, 225));
        addressTextArea.setColumns(20);
        addressTextArea.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        addressTextArea.setRows(5);
        jScrollPane2.setViewportView(addressTextArea);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Add Person Records");

        addJButton.setBackground(new java.awt.Color(237, 238, 225));
        addJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        addJButton.setText("Add Details");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        backJButton.setBackground(new java.awt.Color(237, 238, 225));
        backJButton.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        backJButton.setText("<< Back");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(fnameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(23, 23, 23)
                                        .addComponent(emailJTextField)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(wPhoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(lnameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ssnJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(birthdateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addJButton)
                        .addGap(192, 192, 192))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fnameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lnameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ssnJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wPhoneJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(emailJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(birthdateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addJButton)
                    .addComponent(backJButton))
                .addGap(113, 113, 113))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void wPhoneJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wPhoneJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wPhoneJTextFieldActionPerformed

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        String firstName = fnameJTextField.getText().trim();
        String lastName = lnameJTextField.getText().trim();
        String SSN = ssnJTextField.getText();
        String email = emailJTextField.getText();
        String workPhone = wPhoneJTextField.getText().trim();
        DateFormat df = new SimpleDateFormat("MM/DD/YYYY");
        Date birthdate = new Date();
        String address = addressTextArea.getText().trim();
        
        if(validateName(firstName) && validateName(lastName)){
            if(validateSSN(SSN) && !personDirectory.getPersonList().containsKey(SSN)){
                if(validateEmail(email)){
                    if(validatePhone(workPhone)){
                        try{
                            birthdate = new Date(birthdateTextField.getText());
                            
                        }
                        catch(Exception e){
                            JOptionPane.showMessageDialog(birthdateTextField, "Please Enter Valid Date (MM/DD/YYYY)");
                            birthdateTextField.setText("");
                        }
                        if(!address.isEmpty()){
                            Person newPerson = new Person();
                            
                            newPerson.setEmail(email);
                            newPerson.setFirstName(firstName);
                            newPerson.setLastName(lastName);
                            newPerson.setSSN(SSN);
                            newPerson.setBirthdate(birthdate);
                            newPerson.setAddress(address);
                            newPerson.setPhoneNum(workPhone);
                            
                            personDirectory.addPerson(newPerson);    //Add person for future records
                            JOptionPane.showMessageDialog(null, "Records for "+ newPerson.getFirstName() + " are added!");
                            resetFields();
        
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Please Enter Valid Address");
                            addressTextArea.setText("");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Please Enter 10 digit Phone Number");
                        wPhoneJTextField.setText("");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Please Enter Valid Email");
                    emailJTextField.setText("");
                }
            }
            else{
               JOptionPane.showMessageDialog(null, "Please Enter Valid SSN (DDD-DD-DDDD)"); 
               ssnJTextField.setText("");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Valid Names");
            fnameJTextField.setText("");
            lnameJTextField.setText("");
        }
    }//GEN-LAST:event_addJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField birthdateTextField;
    private javax.swing.JTextField emailJTextField;
    private javax.swing.JTextField fnameJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lnameJTextField;
    private javax.swing.JTextField ssnJTextField;
    private javax.swing.JTextField wPhoneJTextField;
    // End of variables declaration//GEN-END:variables
    
    public void resetFields(){
        fnameJTextField.setText("");
        lnameJTextField.setText("");
        ssnJTextField.setText("");
        emailJTextField.setText("");
        wPhoneJTextField.setText("");
        addressTextArea.setText("");
        birthdateTextField.setText("");
    }
    
    public static boolean validateSSN(String SSN)
    {
        return SSN.matches("^(?!000|666)[0-8][0-9]{2}-(?!00)[0-9]{2}-(?!0000)[0-9]{4}$");
    } 
    
    public static boolean validateName( String firstName )
    {
      return firstName.matches( "[A-Z][a-zA-Z]*" );
    }
    
    public static boolean validatePhone(String phoneNum)
    {
        if(phoneNum.matches("\\d{10}"))
            return true;
        else if(phoneNum.matches("\\d{3}[-\\.\\s]\\d{3}[-\\.\\s]\\d{4}"))
            return true;
        else
            return false;
        
    }   
    
    public static boolean validateEmail(String email)
    {
        return email.matches("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
    }
    
}
